### ISSUE TITLE
Reacji counts not updated when switching between posts using "Recent Posts"

### ISSUE THREAD

**Issue by mwarkentin** [getsentry/vanguard#39]
### Steps to Reproduce

1. Open a post, scroll down, check out reaction counts
2. Click on another post in "Recent Posts" list
3. Scroll down, see identical reaction counts

### Expected Result

I thought I would see the correct reaction count for the 2nd post viewed.

### Actual Result

![vanguard-reacji-counts](https://user-images.githubusercontent.com/67560/182906255-004993ff-f6e1-4bfe-9863-e4b2d2d666c1.gif)

**Comment by dcramer** [comment]
Im convinced this is a Remix bug, that I'm not actually sure how we're supposed to solve. Its your typical React re-render issue, that you'd normally force re-render on parent route change, but we dont actually manage that within Remix.

**Comment by dcramer** [comment]
Lets see if this resolves it: https://github.com/getsentry/vanguard/commit/0274b78adf9602c78c435f09a29db9308ce9ce41

I think its an issue with equality tests
