### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by dcramer** [getsentry/vanguard#7]
While we intentionally did not add comments in the first revision, it probably makes sense to enable a wider conversation on topics.

Spec likely includes the ability to turn comments off per post and per category.

**Comment by dcramer** [comment]
Going to work on comments.

Open question for what the spec is...

- Obv ability to post/read comments in the UI (going to do threadless)
- Should they send an email? To the author? To the same therad as the original email? Could get noisey if we put it into the email therad.
- Anything we're missing?

**Comment by mitsuhiko** [comment]
Probably one question is if comments keep the author name for former employees or if they turn into anonymous. I really favor the former, we lost a lot of context on comments on notion due to the latter.

**Comment by dcramer** [comment]
@mitsuhiko no problems there - its all stored in the db so nothing gets lost
