### ISSUE TITLE
Improve reaction picker

### ISSUE THREAD

**Issue by dcramer** [getsentry/vanguard#8]
Its a fixed set of default emojis right now, which works fine (and also helps promote positive reactions vs e.g. 💩 ) but it would be nice to emulate (aka rip off) something like GitHub's approach here.

**Comment by ckj** [comment]
💯. That's what I had in mind with the mocks -- a '+' button that pops up a grid of possible emojis, with only reactions w/ a count showing on the surface

**Comment by chadwhitacre** [comment]
> GitHub's approach here

They only offer a fixed site like Vanguard does currently, no?

Reactions are useful for sorting by most reacted, good for automating what counts as a "[moment](https://vanguard.getsentry.net/about)." (e.g., homepage shows top moments from past quarter/year based on reaction count).

**Comment by chadwhitacre** [comment]
[Confirmed working](https://vanguard.getsentry.net/p/cl6o5iwc681700ks6edxwdn51).

<img width="569" src="https://user-images.githubusercontent.com/134455/184755726-f03bec1c-e938-47f6-a7b9-9c0a16e1a916.png">

Heart emoji looks like 💩 in both Arc (do they use Chromium? 🤔) and Chrome.

**Comment by chadwhitacre** [comment]
Looks like they're ordered by most clickers now, too. 👍

**Comment by chadwhitacre** [comment]
(And [yes](https://www.reddit.com/r/browsers/comments/vdhge5/arc_browser_new_browser_based_on_chromium/).)
