### ISSUE TITLE
Searching for multiple terms causes Internal Server Error

### ISSUE THREAD

**Issue by kahest** [getsentry/vanguard#85]
### Steps to Reproduce

- Search for e.g. `term1 term2`

### Expected Result

Performs search using the specified terms and presents results

### Actual Result

Internal Server Error

**Comment by dcramer** [comment]
we have fixed sentry so have an actual stack to go w/ this now https://sentry.io/share/issue/82f36cb3110a434e9d4f64e3bb1b731e/

**Comment by dcramer** [comment]
So the tl;dr is my understanding of postgres search was wrong. It actually requires a special syntax. Need to rethink how search is implemented.
