### ISSUE TITLE
Images don't survive email

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/vanguard#91]
### Steps to Reproduce

1. Post on Vanguard.
2. Check email.

### Expected Result

Images.

### Actual Result

No images.

Cf. https://vanguard.getsentry.net/p/clbcz8d6n11320ks6gz9dhfku vs. ...

<img width="745" alt="Screen Shot 2022-12-07 at 2 37 55 PM" src="https://user-images.githubusercontent.com/134455/206279043-b0843538-6a04-4453-9bcd-ce3d6b67ef8a.png">

**Comment by silent1mezzo** [comment]
Seems to be fixed now
